services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "4000:4000"
    #env_file: /home/ubuntu/.env
    depends_on:
      - rabbitmq
    networks:
      - app-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  email-worker:
    build:
      context: ./email-worker
    command: ["node", "emailWorker.js"]
    #env_file: /home/ubuntu/.env
    depends_on:
      - rabbitmq
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
